[server]
headless = true
port = 8501
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
base = "dark"
# The primary color represents the "Start Investigation" primary button background
primaryColor = "#00c853"
